// Generated by CoffeeScript 1.12.3
var mask, name, output, superhero, weapon;

name = "Jim Carrey";

mask = "The Mask";

weapon = "Laughter";

superhero = {
  name: name,
  mask: mask,
  weapon: weapon
};

output = turtle.name + " wears an " + turtle.mask + " as a mask. Watch out for his " + turtle.weapon + "!";
